on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-terraform-infra:
    name: 'Deploy Terraform state bucket'
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    defaults:
      run:
        shell: bash
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}

      - name: Deploy state bucket
        run: |
          set -a 
          source .env
          az group create \
            -l $STATE_RESOURCE_GROUP_LOCATION \
            -n $STATE_RESOURCE_GROUP_NAME
          az storage account create \
            -n $STATE_STORAGE_ACCOUNT_NAME \
            -g $STATE_RESOURCE_GROUP_NAME \
            -l $STATE_RESOURCE_GROUP_LOCATION \
            --sku Standard_LRS \
            --allow-blob-public-access false
          az storage container create \
            --name tfstate \
            --account-name $STATE_STORAGE_ACCOUNT_NAME