on:
  workflow_dispatch:

jobs:
  deploy-terraform-infra:
    name: 'Deploy Terraform state bucket'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy state bucket
        run: |
          set -a 
          source .env.backend
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENTID }} \
            -p ${{ secrets.AZURE_TENANTID }} \
            --tenant ${{ secrets.AZURE_SUBSCRIPTIONID }}
          az group create \
            -l $STATE_RESOURCE_GROUP_LOCATION \
            -n $STATE_RESOURCE_GROUP_NAME
          az storage account create \
            -n $STATE_STORAGE_ACCOUNT_NAME \
            -g $STATE_RESOURCE_GROUP_NAME \
            -l $STATE_RESOURCE_GROUP_LOCATION \
            --sku Standard_LRS \
            --allow-blob-public-access false
          az storage container create \
            --name tfstate \
            --account-name $STATE_STORAGE_ACCOUNT_NAME